config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'callbacks' }
  root 'games#index'

  resources :pieces, only: %i[show update] do
    get :castle
    get :reload
    put :promotion
  end

  resources :games, only: %i[index new create show] do
    get :update_invited_user, :surrender, :draw, :reload
  end

  mount ActionCable.server, at: '/cable'
end

app/models/game.rb
# frozen_string_literal: true

class Game < ApplicationRecord
  belongs_to :creating_user, :class_name => 'User', :foreign_key => 'creating_user_id'
  belongs_to :invited_user, :class_name => 'User', :foreign_key => 'invited_user_id', optional: true
  belongs_to :winner, :class_name => 'User', :foreign_key => 'winner_id', optional: true
  has_many :moves, dependent: :destroy 
  has_many :comments, dependent: :destroy
  has_many :pieces, dependent: :destroy
  before_create :assign_default_player
  scope :available, -> { where(invited_user_id: nil) }

  def assign_default_player
    write_attribute(:p1_id, creating_user.id)
  end

  def randomly_assign_players(current_user)
    other_player = creating_user
    if rand(1..1000) <= 500
      update(p1_id: other_player.id, p2_id: current_user.id)
    else
      update(p1_id: current_user.id, p2_id: other_player.id)
    end
  end

  def opponent(current_user)
    current_user.id == p1_id ? player_two : player_one
  end

  def player_one
    return nil if p1_id.nil?
    return User.find(p1_id)
  end

  def player_two
    return nil if p2_id.nil?
    return User.find(p2_id)
  end

  def player_one=(u)
    write_attribute(:p1_id, u.id)
  end

  def player_two=(u)
    write_attribute(:p2_id, u.id)
  end

  def get_player_one 
    return (not player_one.nil?) ? player_one.email : "No Player One"
  end

  def get_player_two
    return (not player_two.nil?) ? player_two.email : "No Player Two"
  end

  
  def check?(white)
    king = pieces_for_color(white).select { |piece| piece.type == 'King' }.first
    return false unless king

    enemies = get_enemies(king)
    enemies.any? { |enemy| enemy.can_take?(king) }
  end

  def pieces_for_color(white)
    pieces.select { |piece| piece.is_white? == white }
  end


  def checkmate?(white)
    return false unless check?(white)
    return false if legal_moves(white) 
    true
  end

  def end_game(piece)
    if piece.is_white?
      update(winner_id: p1_id)
    else
      update(winner_id: p2_id)
    end
  end

  def populate_game
    # White Rooks
    pieces.create(x_position: 0, y_position: 0, piece_number: 0, type: 'Rook')
    pieces.create(x_position: 0, y_position: 7, piece_number: 0, type: 'Rook')
    # White Knights
    pieces.create(x_position: 0, y_position: 1, piece_number: 1, type: 'Knight')
    pieces.create(x_position: 0, y_position: 6, piece_number: 1, type: 'Knight')
    # White Bishops
    pieces.create(x_position: 0, y_position: 2, piece_number: 2, type: 'Bishop')
    pieces.create(x_position: 0, y_position: 5, piece_number: 2, type: 'Bishop')
    # White Queen
    pieces.create(x_position: 0, y_position: 3, piece_number: 3, type: 'Queen')
    # White King
    pieces.create(x_position: 0, y_position: 4, piece_number: 4, type: 'King')
    # White Pawns
    8.times do |y|
      pieces.create(x_position: 1, y_position: y, piece_number: 5, type: 'Pawn')
    end
    # Black Rooks
    pieces.create(x_position: 7, y_position: 0, piece_number: 6, type: 'Rook')
    pieces.create(x_position: 7, y_position: 7, piece_number: 6, type: 'Rook')
    # Black Knights
    pieces.create(x_position: 7, y_position: 1, piece_number: 7, type: 'Knight')
    pieces.create(x_position: 7, y_position: 6, piece_number: 7, type: 'Knight')
    # Black Bishops
    pieces.create(x_position: 7, y_position: 2, piece_number: 8, type: 'Bishop')
    pieces.create(x_position: 7, y_position: 5, piece_number: 8, type: 'Bishop')
    # Black Queen
    pieces.create(x_position: 7, y_position: 3, piece_number: 9, type: 'Queen')
    # Black King
    pieces.create(x_position: 7, y_position: 4, piece_number: 10, type: 'King')
    # Black Pawns
    8.times do |y|
      pieces.create(x_position: 6, y_position: y, piece_number: 11, type: 'Pawn')
    end
  end

  def can_claim_draw?(current_user)
    return true if stalemate?(current_user)
    return true if threefold_repetition?
    return true if fifty_move_rule?
    return false
  end

  def stalemate?(current_user)
    return false if state == 'Black King in Check.'
    return false if state == 'White King in Check.'
    return false if enough_pieces_remaining(current_user.id == p1_id)
    return false if legal_moves(current_user.id == p1_id)
    return true
  end

  def legal_moves(white)
    legal_moves = []
    playable_pieces(white).each do |piece|
      8.times do |x|
        8.times do |y|
          next if !piece.valid_move?(x,y)
          next if piece.puts_self_in_check?(x,y)
          legal_moves << piece
        end
      end
    end
    return legal_moves.present?
  end

  def enough_pieces_remaining(white) # A check to not do legal moves if the player has enough remaining pieces
    return playable_pieces(white).count > 3
  end

  def playable_pieces(white)
    playable_pieces = []
    pieces_for_color(white).each do |piece|
      next if piece.x_position == 8 || piece.x_position == 9
      playable_pieces << piece 
    end
    return playable_pieces
  end

  def threefold_repetition? # This one has me beat for now
    return false
  end

  def fifty_move_rule?
    return false if moves.count <= 100
    # The limit is 100 since a move in our app is only one player but in chess is for each player
    last_fifty_moves = moves.order(updated_at: :desc).limit(100) 
    return false if pawn_was_moved?(last_fifty_moves)
    return false if piece_was_captured?(last_fifty_moves)
    return true 
  end

  def pawn_was_moved?(last_fifty_moves)
    pawn_moves = last_fifty_moves.find do |move|
      move.start_piece == 5 || move.start_piece == 11
    end

    return pawn_moves.present?
  end

  def piece_was_captured?(last_fifty_moves)
    last_white_player_capture = pieces.where(x_position: 8).order('updated_at').last
    last_black_player_capture = pieces.where(x_position: 9).order('updated_at').last
    # The if statements are to catch if the game has zero captures. A highly unlikely scenario but easy to fix.
    if last_white_player_capture && last_black_player_capture
      return true if last_fifty_moves.last.updated_at < last_white_player_capture.updated_at 
      return true if last_fifty_moves.last.updated_at < last_black_player_capture.updated_at
      return false
    end
    if last_white_player_capture 
      return true if last_fifty_moves.last.updated_at < last_white_player_capture.updated_at
      return false
    end
    if last_black_player_capture
      return true if last_fifty_moves.last.updated_at < last_black_player_capture.updated_at
      return false
    end
    return false
  end
end

app/controllers/games_controller.rb
# frozen_string_literal: true

class GamesController < ApplicationController
  before_action :authenticate_user!, only: %i[new create show update_invited_user surrender draw]

  def index
    @games = Game.all
    if current_user
      @created = Game.where(creating_user_id: current_user.id)
      @joined = Game.where(invited_user_id: current_user.id)
    end
  end

  def new
    @game = Game.new
  end

  def create
    @game = Game.create(game_params.merge(creating_user: current_user))
    if @game.valid?
      @game.populate_game
      redirect_to game_path(@game)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @game = Game.find(params[:id])
  end

  def update_invited_user
    @game = Game.find(params[:game_id])
    @game.update(invited_user_id: current_user.id)
    if @game.valid?
      @game.randomly_assign_players(current_user)
    else
      render :new, status: :unprocessable_entity
    end

    opponent = @game.opponent(current_user)
    ActionCable.server.broadcast "game_channel_user_#{opponent&.id}", game: @game
    ActionCable.server.broadcast "game_channel_user_#{current_user&.id}", path: "games/#{@game.id}"
  end

  def surrender
    @game = Game.find(params[:game_id])
    @game.update(state: 'Surrendered')

    if current_user.id == @game.p1_id
      @game.update(winner_id: @game.p2_id)
    else
      @game.update(winner_id: @game.p1_id)
    end

    redirect_to game_path(@game)
  end

  def draw
    @game = Game.find(params[:game_id])
    @game.write_attribute(:state, 'Draw')
    @game.save

    opponent = @game.opponent(current_user)
    ActionCable.server.broadcast "game_channel_user_#{opponent&.id}", piece: @game.pieces.first

    respond_to do |format|
      format.js { render 'draw' }
    end
  end

  def reload
    @game = Game.find(params[:game_id])
    flash.now[:alert] = []
    flash.now[:alert] << @game.state if @game.state.present?

    respond_to do |format|
      format.js { render 'reload' }
    end
  end

  private

  def game_params
    params.require(:game).permit(:name)
  end
end

app/helpers/games_helper.rb
# frozen_string_literal: true

module GamesHelper
  include ActionView::Helpers::TagHelper

  def get_piece(x, y, game)
    return game.pieces.where(x_position: x, y_position: y).first
  end

  def black_tile?(x,y)
    return (x % 2 == 0 && y % 2 == 0 || x % 2 == 1 && y % 2 == 1)
  end

  def white_king
    return @game.pieces.where(piece_number: 4).first
  end
  
  def white_queenside_rook
    return @game.pieces.where(x_position: 0, y_position: 0).first
  end

  def white_kingside_rook
    return @game.pieces.where(x_position: 0, y_position: 7).first
  end

  def black_king
    return @game.pieces.where(piece_number: 10).first
  end
  
  def black_queenside_rook
    return @game.pieces.where(x_position: 7, y_position: 0).first
  end

  def black_kingside_rook
    return @game.pieces.where(x_position: 7, y_position: 7).first
  end

  def captured_black_pieces
    return @game.pieces.where(x_position: 8)
  end

  def captured_white_pieces
    return @game.pieces.where(x_position: 9)
  end

  def players_piece?(piece)
    return piece.is_white? && piece.game.player_one == current_user || !piece.is_white? && piece.game.player_two == current_user
  end

  def your_turn?
    last_move = @game.pieces.order('updated_at').last.moves.order('updated_at').last
    if last_move.nil? then
      return @game.player_one == current_user
    elsif last_move.start_piece > 5 
      return @game.player_one == current_user
    elsif last_move.start_piece < 6
      return @game.player_two == current_user
    else
      return false
    end
  end

  def player_ones_turn?
    last_move = @game.pieces.order('updated_at').last.moves.order('updated_at').last
    return true if last_move.nil?
    return true if last_move.start_piece > 5
    return false 
  end

  def player_twos_turn?
    last_move = @game.pieces.order('updated_at').last.moves.order('updated_at').last
    return false if last_move.nil?
    return true if last_move.start_piece < 6
    return false 
  end
  
  def can_move_piece?(piece)
    return piece.present? && players_piece?(piece) && your_turn? && @game.state != 'Draw' && @game.winner.nil?
  end

  def can_not_move_piece?(piece)
    return true if piece.present? && !players_piece?(piece) 
    return true if piece.present? && !your_turn? 
    return true if piece.present? && @game.state == 'Draw'
    return true if piece.present? && @game.winner.present?
    return false
  end
end

app/views/games/_board.html.erb
<% if flash.now[:alert].present? %>
  <div class="deliver-message alert alert-danger">
    <% flash.now[:alert].each do |alert| %>
      <%= alert %>
    <% end %>
  </div>
<% end %>
<% if @game.state == 'Draw' %>
  <div class="row justify-content-center"><h3>This game is over. It ended in a draw!</h3></div>
<% end %>
<% if @game.winner != nil %>
  <div class="row justify-content-center"><h3>This game is over.<%= @game.winner.email %> has won! </h3></div>
<% end %>
<% 8.times do |y| %>
  <div class="row justify-content-center">
    <% 8.times do |x| %>
      <div id="<%= x %>-<%= y %>" data-x-coord=<%= x %> data-y-coord=<%= y %> class="<%= black_tile?(x,y) ? "black tile" : "white tile" %>">
        <% piece = get_piece(x, y, @game) %>
        <% if can_move_piece?(piece) %>
          <%= image_tag piece.piece_number.to_s + ".png", 
                class: 'piece', 
                data: {piece_id: piece.id} %>
        <% end %>
        <% if can_not_move_piece?(piece) %>
          <%= image_tag piece.piece_number.to_s + ".png", 
                class: 'piece2',
                data: {piece_id: piece.id} %>
        <% end %>
      </div>
    <% end %>
  </div>
<% end %>

app/views/games/_player_one.html.erb
<h4 class="<%= player_ones_turn? ? "your-turn" : "not-your-turn" %>">
  <%= @game.get_player_one %>
  <br />
</h4>
<div class="row justify-content-center">
  <% if can_white_queenside_castle?(white_queenside_rook) %>
    <%= link_to "White Queen Side Castle", piece_castle_path(piece_id: white_king, rook_id: white_queenside_rook), 
              method: :get, remote: true, data: {confirm: 'Are you sure you want to Castle?'},
              class: 'btn btn-secondary' %>
  <% end %>
  <% if can_white_kingside_castle?(white_kingside_rook) %>
    <%= link_to "White King Side Castle", piece_castle_path(piece_id: white_king, rook_id: white_kingside_rook), 
              method: :get, remote: true, data: {confirm: 'Are you sure you want to Castle?'},
              class: 'btn btn-secondary' %>
  <% end %>
  <% if @game.can_claim_draw?(current_user) && current_user == @game.player_one && @game.state != 'Draw' && your_turn? %>
    <%= link_to "Claim a draw", game_draw_path(@game), method: :get, remote: true, 
            data: {confirm: 'Are you sure you want to end this game in a draw?'},
            class: 'btn btn-secondary' %>
  <% end %>
</div>       
<hr />
<h3>Captured Pieces</h3>
<br />
<% captured_black_pieces.each do |piece| %>
  <div class="captured"><%= image_tag piece.piece_number.to_s + ".png", class: "piece2" %></div>
<% end %>

app/views/games/_player_two.html.erb
<h4 class="<%= player_twos_turn? ? "your-turn" : "not-your-turn" %>">
  <%= @game.get_player_two %>
  <br />
</h4>
<div class="row justify-content-center">  
  <% if can_black_queenside_castle?(black_queenside_rook) %>
    <%= link_to "Black Queen Side Castle", piece_castle_path(piece_id: black_king, rook_id: black_queenside_rook), 
              method: :get, remote: true, data: {confirm: 'Are you sure you want to Castle?'},
              class: 'btn btn-secondary' %>
    <% end %>
  <% if can_black_kingside_castle?(black_kingside_rook) %>
    <%= link_to "Black King Side Castle", piece_castle_path(piece_id: black_king, rook_id: black_kingside_rook), 
              method: :get, remote: true, data: {confirm: 'Are you sure you want to Castle?'},
              class: 'btn btn-secondary' %>
  <% end %>
  <% if @game.can_claim_draw?(current_user) && current_user == @game.player_two && @game.state != 'Draw' && your_turn? %>
  <%= link_to "Claim a draw", game_draw_path(@game), method: :get, remote: true, 
            data: {confirm: 'Are you sure you want to end this game in a draw?'},
            class: 'btn btn-secondary' %>
  <% end %>
</div>    
<hr />
<h3>Captured Pieces</h3>
<br />
<% captured_white_pieces.each do |piece| %>
  <div class="captured"><%= image_tag piece.piece_number.to_s + ".png", class: "piece2" %></div>
<% end %>

app/views/games/draw.js.erb
$('.game-board').html('<%= j (render partial: 'games/board') %>');
$('.player-one').html('<%= j (render partial: 'games/player_one') %>');
$('.player-two').html('<%= j (render partial: 'games/player_two') %>');
init_draggables_and_droppables();

app/views/games/index.html.erb
<div class="hero">
  
  <br />
  <div class="col-10 offset-1 text-center">
  <%# Wanted to add a create game button for when someone is logged in and there are games to join. Otherwise there is only the link on the nav bar. %>
    
    <div class="row text-center">
      <div class="col-12 col-sm">
        <% if @created.present? %>
          <ul class="list-group">
            <h3>Created Games</h3>
                <% @created.each do |game| %>
                  <li class="list-group-item">
                    <h4><%= link_to game.name, game_path(game) %></h4>
                  </li>
                <% end %>
          </ul>
        <% end %>
      </div>
      <div class="col-12 col-sm">
        <% if @joined.present? %>
          <ul class="list-group">
            <h3>Joined Games</h3>
                <% @joined.each do |game| %>
                  <li class="list-group-item text-center">
                    <h3><%= link_to game.name, game_path(game) %></h3>
                  </li>    
                <% end %>
          </ul>
        <% end %>
      
      </div>

      <div class="col-12 col-sm">
        <% if @games.available.present? %>
          <ul class="list-group">
            <h3>Available Games</h3>
            <% @games.available.each do |game| %>
              <li class="list-group-item">
                <h4><%= game.name %></h4> &nbsp &nbsp &nbsp 
                <%= link_to "Join", game_update_invited_user_path(game), remote: true,
                    method: :get, data: {confirm: 'Are you sure you want to join?'},
                    class: 'btn btn-outline-info' %>
              </li>
            <% end %>
          </ul>
      </div>
    </div>
  </div>
</div>
<div class="col-10 offset-1 text-center">
  <% else %>
    <h3>No games available to join. <%= link_to 'New Game', new_game_path, class: 'btn btn-primary'%></h3>
  <% end %>
</div>
    
  

app/views/games/new.html.erb
<div class="col-10 offset-1">
  <h1>Start a new game</h1>
    <%= simple_form_for @game do |f| %>
      <%= f.input :name %>
      <%= f.submit 'Start', class: 'btn btn-primary' %>
    <% end %>
</div>

app/views/games/reload.js.erb
$('.game-board').html('<%= j (render partial: 'games/board') %>');
$('.player-one').html('<%= j (render partial: 'games/player_one') %>');
$('.player-two').html('<%= j (render partial: 'games/player_two') %>');
init_draggables_and_droppables();

app/views/games/show.html.erb
<div class="col-8 offset-2 text-center">
  <h2><%= @game.name %></h2>
</div>

<br />

<div class="row">
  <div class="player-one col-lg text-center">
    <%= render partial: 'player_one' %>
  </div>
  <div class="game-board col-lg-auto">
    <%= render partial: 'board' %>
  </div>
  <div class="player-two col-lg text-center">
    <%= render partial: 'player_two' %>
  </div>
</div>

<script type='text/javascript'>
  function init_draggables_and_droppables() { 
      $('.piece').draggable({
        containment: '.gameboard',
        snap: '.tile',
        cursor: 'crosshair',
        scroll: false
      });

      $('.tile').droppable({
        drop: function( event, ui ) {
          piece_id = ui.draggable.data('piece-id')
          x_position = $(this).data('x-coord')
          y_position = $(this).data('y-coord')
          $.ajax({
            url: `/pieces/${piece_id}?x_position=${x_position}&y_position=${y_position}`,
            type: 'PUT'
          });
        }
      });
    }
  
  $(function() {
    init_draggables_and_droppables();
  });
</script>